source 'http://rubygems.org'

ruby '2.1.2'

gem 'bson_ext'
gem 'mongo_mapper'
gem 'multi_json', '1.6.1'
gem 'octokit'
gem 'oauth'
gem 'pry'
gem 'rake'
gem 'sidekiq'
gem 'sinatra'
gem 'toml', '0.0.3'
gem 'activesupport', '~> 4.1.4'
